application: etchcodeusercontent
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /play/
  static_files: play/index.html
  upload: play\/index\.html

- url: /play/(.+)
  static_files: play/\1
  upload: play\/(.+)
  
- url: /embed/(.+)
  static_files: embed/\1
  upload: embed\/(.+)

libraries:
- name: webapp2
  version: "2.5.2"
